/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/registration/registration.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '../../../../src/app/registration/registration.service';
class RegistrationModuleInjector extends import0.ɵNgModuleInjector<import1.RegistrationModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _ReactiveFormsModule_2:import3.ReactiveFormsModule;
  _RegistrationModule_3:import1.RegistrationModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  __FormBuilder_5:import3.FormBuilder;
  __ɵi_6:import3.ɵi;
  __RegistrationService_7:import4.RegistrationService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  get _FormBuilder_5():import3.FormBuilder {
    if ((this.__FormBuilder_5 == null)) { (this.__FormBuilder_5 = new import3.FormBuilder()); }
    return this.__FormBuilder_5;
  }
  get _ɵi_6():import3.ɵi {
    if ((this.__ɵi_6 == null)) { (this.__ɵi_6 = new import3.ɵi()); }
    return this.__ɵi_6;
  }
  get _RegistrationService_7():import4.RegistrationService {
    if ((this.__RegistrationService_7 == null)) { (this.__RegistrationService_7 = new import4.RegistrationService()); }
    return this.__RegistrationService_7;
  }
  createInternal():import1.RegistrationModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._ReactiveFormsModule_2 = new import3.ReactiveFormsModule();
    this._RegistrationModule_3 = new import1.RegistrationModule();
    return this._RegistrationModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_2; }
    if ((token === import1.RegistrationModule)) { return this._RegistrationModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_5; }
    if ((token === import3.ɵi)) { return this._ɵi_6; }
    if ((token === import4.RegistrationService)) { return this._RegistrationService_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const RegistrationModuleNgFactory:import0.NgModuleFactory<import1.RegistrationModule> = new import0.NgModuleFactory<any>(RegistrationModuleInjector,import1.RegistrationModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovQW5ndWxhcjJEZXBsb3ltZW50L3NyYy9hcHAvcmVnaXN0cmF0aW9uL3JlZ2lzdHJhdGlvbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovQW5ndWxhcjJEZXBsb3ltZW50L3NyYy9hcHAvcmVnaXN0cmF0aW9uL3JlZ2lzdHJhdGlvbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
